export const PRODUCT_STATUS = {
  WAITING_FOR_APPROVAL: 'WAITING_FOR_APPROVAL',
  ACTIVE: 'ACTIVE',
  REJECT: 'REJECT',
  OPNAME: 'OPNAME',
  DELETE: 'DELETE',
}

export const LIST_VIEW_TYPES = {
  TABLE: 'TABLE',
  GRID: 'GRID'
}